version: "3"
services:
  api-database3:
    image: mongo:3.2.4
    container_name: "api-database3"
    ports:
      - 27017:27017
    command: --smallfiles
  note:
    image: note:latest
    restart: always
    container_name: note
    ports:
      - 9031:9031
    # links:
    #   - api-database3