version: "3"
services:
  mysqldb3:
    image: mysql:5.6
    ports:
      - "3306:3306"
    networks:
      - project9-mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo9

  patient:
    image: patient
    ports:
      - "9030:9030"
    networks:
      - project9-mysql
    depends_on:
      - mysqldb3

networks:
  project9-mysql:
    driver: bridge